# Generated by Django 4.2 on 2024-07-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('company_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('responsible_name', models.CharField(max_length=255)),
                ('state_registration', models.CharField(max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.BooleanField(default=False)),
                ('cell_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('confirm_email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=9)),
                ('number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=100)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
