# Generated by Django 4.2 on 2024-08-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_company_ddd_cp_company_ddd_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type_company',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
