# Generated by Django 4.2 on 2024-07-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_alter_company_email_alter_company_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
