# Generated by Django 4.2 on 2024-08-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0009_review_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
