# Generated by Django 4.2 on 2024-08-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0010_rename_review_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='segment',
            field=models.CharField(default='automotivo', max_length=100),
            preserve_default=False,
        ),
    ]
